### ISSUE TITLE
connecting backbone peptides throws NoSuchElementException when backbone atoms are missing

### ISSUE THREAD

**Issue by enauz** [cleberecht/singa#22]
- when backbone atoms are missing, connecting the backbone fails
`java.util.NoSuchElementException
	at java.util.Optional.orElseThrow(Optional.java:290)
	at de.bioforscher.chemistry.physical.proteins.Residue.getAtomByName(Residue.java:142)
	at de.bioforscher.chemistry.physical.proteins.Residue.getBackboneCarbon(Residue.java:169)
	at de.bioforscher.chemistry.physical.proteins.Chain.connectPeptideBonds(Chain.java:88)
	at de.bioforscher.chemistry.physical.proteins.Chain.connectChainBackbone(Chain.java:71)
	at de.bioforscher.chemistry.parser.pdb.StructureAssembler.lambda$assembleStructure$1(StructureAssembler.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at de.bioforscher.chemistry.parser.pdb.StructureAssembler.assembleStructure(StructureAssembler.java:99)
	at de.bioforscher.chemistry.parser.pdb.PDBParserService.parsePDBFile(PDBParserService.java:34)
	at de.bioforscher.chemistry.algorithms.superimposition.SubStructureSuperimposerTest.setUp(SubStructureSuperimposerTest.java:27)`

**Comment by cleberecht** [comment]
this is fixed since 807d917

now we check if the atoms, that should be connected are present if not no edge is created
